<?php

/* Implementation of hook_block */
function twitter_block($op = 'list', $delta = 0, $edit = array()) {
  switch($op) {
    case 'list':
      $blocks[0]['info'] = t('Twitter User Timeline');
      return $blocks;
    case 'configure':
      $form = array();
      return $form;
    case 'save':
      return;
    case 'view': default:
      switch($delta) {
        case 0:
          $block['subject'] = t('debug');
          $block['content'] = "<pre>" . htmlspecialchars(user_timeline()) . "</pre>";
    }
    return $block;    
  }
}

function user_timeline($n = 10) {
  $pr = curl_init("http://twitter.com/statuses/user_timeline.xml?screen_name=hairymnstr");
  ob_start();
  curl_exec($pr);
  $res = ob_get_contents();
  ob_end_clean();
  curl_close($pr);
  return $res;
}

?>
